FROM node:14-alpine

ARG ENV=development
ARG MAIN_DIR=techstore
ARG WORKPLACE_PATH=/opt/source

ENV NODE_ENV=development
ENV NODE_OPTIONS=--max-old-space-size=4096

LABEL edu.cibertec.techstore.project.name="Tech Store" \
    edu.cibertec.techstore.project.key="techstore" \
    edu.cibertec.techstore.project.version="1.0" \
    edu.cibertec.techstore.project.description="Tech Store Application" \
    edu.cibertec.techstore.author.name="Christian Rivera" \
    edu.cibertec.techstore.author.email="crivera2093@gmail.com" \
    edu.cibertec.techstore.author.url="https://github.com/pSharpX"

WORKDIR ${WORKPLACE_PATH}/${MAIN_DIR}

COPY env_secrets_expand.sh env_secrets_expand.sh
COPY entrypoint.sh entrypoint.sh
COPY package.json package.json
COPY . .

RUN chmod +x env_secrets_expand.sh entrypoint.sh
RUN npm install

EXPOSE 3000
ENTRYPOINT [ "./entrypoint.sh" ] 
