apiVersion: v1
kind: Service
metadata:
  name: techstore-database-service
spec:
  selector:
    app: techstore
    component: database
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432