apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-persistent-volume
  labels:
    environment: dev
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate