apiVersion: v1
kind: Secret
metadata:
  name: techstore.secret
type: Opaque
data:
  password: eW91cl9kYXRhYmFzZV9wYXNzd29yZA==
stringData:
  PG_USER: your_database_username
  PG_PASSWORD: your_database_password
  PG_DB: techstore.database          
  CD_CLOUD_NAME: your_cloudinary_cloud_name
  CD_UPLOAD_PRESET: your_cloudinary_upload_preset
  CD_API_KEY: your_cloudinary_api_key
  CD_API_SECRET: your_cloudinary_api_secret